[theme]
primaryColor = "#73173F"          # maroon
backgroundColor = "#0E0E0E"       # dark background
secondaryBackgroundColor = "#1A1A1A"
textColor = "#F2F2F2"
font = "monospace"                # typewriter-style
